name: image_picker_master
description: "A comprehensive Flutter plugin for picking images, videos, audio files, documents, and any file type, multiple selection, and file categorization."
version: 0.0.4
homepage: "https://github.com/SwanFlutter/image_picker_master.git"

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:

  plugin:
    platforms:
      android:
        package: com.example.image_picker_master
        pluginClass: ImagePickerMasterPlugin
      ios:
        pluginClass: ImagePickerMasterPlugin
      linux:
        pluginClass: ImagePickerMasterPlugin
      macos:
        pluginClass: ImagePickerMasterPlugin
      windows:
        pluginClass: ImagePickerMasterPluginCApi
      web:
        pluginClass: ImagePickerMasterWeb
        fileName: image_picker_master_web.dart

